name: sixvalley_vendor_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  provider: ^6.1.1
  connectivity_plus: ^6.1.1
  dio: ^5.4.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  image_picker: ^1.0.5
  flutter_switch: ^0.3.2
  cached_network_image: ^3.3.1
  flutter_typeahead: ^5.2.0
  autocomplete_textfield: ^2.0.1
  dotted_border: ^2.1.0
  flutter_html: ^3.0.0-alpha.2
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0
  path_provider: ^2.1.1
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.12
  permission_handler: ^11.1.0
  barcode_widget: ^2.0.4
  file_picker: ^8.1.7
  url_launcher: ^6.2.2
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3
  flutter_speed_dial: ^7.0.0
  barcode_scan2: ^4.5.1
  # flutter_barcode_scanner: ^2.0.0
  #flutter_pos_printer_platform: 1.1.0
  #flutter_pos_printer_platform_image_3_sdt: ^1.1.8
  print_bluetooth_thermal: ^1.1.6
  screenshot: ^3.0.0
  #flutter_pos_printer_platform_image_3: ^1.2.0
  esc_pos_utils: ^1.1.0
  flutter_slidable: ^3.0.1
  readmore: ^3.0.0
  flutter_html_table: ^3.0.0-beta.2
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  syncfusion_flutter_datepicker: ^28.1.38
  textfield_tags: ^3.0.1
  http: ^1.1.2
  path: ^1.8.2
  typed_data: ^1.3.2
  http_parser: ^4.0.2
  animated_floating_buttons: ^0.0.2
  emoji_picker_flutter: ^4.2.0
  syncfusion_flutter_charts:
  carousel_slider: ^5.0.0
  flutter_downloader: ^1.11.8
  # open_file_plus: ^3.4.1+1
  open_file_safe_plus: ^0.0.6
  open_file_manager: ^1.0.2
  just_the_tooltip: ^0.0.12
  syncfusion_flutter_pdfviewer: ^28.1.38
  video_player: ^2.10.0
  audioplayers: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0


dependency_overrides:
  syncfusion_flutter_core: any


dev_dependencies:
  icons_launcher:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


icons_launcher:
  image_path: "assets/image/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true

flutter_icons:
  ios: true
  android: true
  image_path: "assets/image/logo.png"





flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/ubuntu/Ubuntu-Bold.ttf
          weight: 600